version: "3.8"

services:
  jest:
    image: node:16
    depends_on:
      - db
    working_dir: /usr/src/app
    container_name: next-app-jest
    command: yarn jest
    env_file: .dev.env
    volumes:
      - ./app:/usr/src/app
  db:
    image: postgres
    env_file:
      - .dev.env
    ports:
      - "5432:5432"
