version: "3.8"

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-app-dev
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:cached
      - ${SSH_KEY_PATH:-~/.ssh/id_rsa}:/root/.ssh/id_rsa:ro
      # node modules are stored in an isolated volume which is not shown in host OS directory listing.
      # This improves performance.
      - node_modules:/usr/src/app/node_modules
  db:
    image: postgres:14
    restart: always
    tty: true
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  db-data:
  node_modules:
