version: "3.8"

services:
  next:
    image: node:16
    container_name: next-app-dev
    tty: true
    command: yarn dev
    working_dir: /usr/src/app
    env_file: .dev.env
    depends_on:
      - redis
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - cache:/data
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .dev.env
    ports:
      - "5432:5432"

volumes:
  cache:
  db-data:
