version: '3.8'

services:
  frontend:
    image: bilis-back-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    container_name: bilis-back-dev