name: CI tests

on:
#  pull_request:
#    branches: '*'
  push:
    branches: 'cypress'

jobs:
#  test-unit:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '19.x'
#      - name: Install dependencies
#        run: yarn --frozen-lockfile
#      - name: Run tests
#        run: yarn test

  test-integration:
    runs-on: ubuntu-latest
    env:
      NODE_ENV="development"
    env: 
      POSTGRES_USER="prodeko"
    env: 
      POSTGRES_DB="bilis"
    env: 
      POSTGRES_PASSWORD="ci"
    env: 
      POSTGRES_HOST="db"
    env: 
      POSTGRES_PORT=5432
    env: 
      NEXT_PUBLIC_API_URL="http://localhost:3000/api"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - name: Printenv
        run: printenv
      - name: Install dependencies
        run: yarn --frozen-lockfile
      #- name: migrations
      #  run: yarn dev:migrate:up
      - name: create test data
        run: yarn dev:create-test-data
      - name: Install cypress
        run: yarn cypress install
      - name: Start dev-server
        run: yarn ci:cypress